- name: Install PHP and packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "php{{ php_version }}"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-xsl"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-iconv"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-mcrypt"